### ISSUE TITLE
Use React JS + Next JS as Documentation Page Stack

### ISSUE THREAD

**Issue by stanleyowen** [fire-ui/fire-ui.github.io#6]

**Comment by vinlegend1** [comment]
**Some suggestions for that**
I'm thinking of creating a new directory within this repository and do all the next js stuff in there. And then for the next js documentation version, I'm thinking of deploying to vercel and we keep fire-ui.github.io the same. Or we can build out everything and host it on netlify... since it's mostly static (I think)

**Comment by kimlimjustin** [comment]
Good idea, but what about this, next js documentation pointed out that you can export next.js into HTML files, so we can export them and host them using Github pages too! However, if my idea doesn't work, I'll rather switch to Vercel. In addition, may I assign you @vinlegend1 to this issue since I'm not very experienced with next js?

**Comment by vinlegend1** [comment]
Sure! I hope you don't mind if I use typescript :)

**Comment by kimlimjustin** [comment]
I don't mind at all :)
